### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by observingClouds**

### CODE REVIEW

**Comment by mariusrixen** [comment]
Dear Hauke, I used the new pysonde release to process the data from ORCESTRA. The sounding_id seems to work for Level 1 data, however I still get '0' for Level 2 data.
Somehow, it seems that the sounding_id is not transferred from level 1 to level 2. Do you know how to fix this ? Or if there might be something wrong in a config file ?

Thanks in advance,
Cheers,
Marius

**Comment by observingClouds** [comment]
@mariusrixen could you try adding `internal_varname: "sounding"` also to the coordinates section of the level2.yaml and see if that fixes the issue.

**Comment by mariusrixen** [comment]
@observingClouds, thanks for your answer. You're right, I added it only for the level1 data, and I thought it would automatically transfer it to the level2.
It works now, thanks a lot for your help !

**Comment by observingClouds** [comment]
Good catch though! I'll add that to the example files.

**Pull request merged**
